name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install deps
        working-directory: app
        run: pnpm i --frozen-lockfile
      - name: Type check
        working-directory: app
        run: pnpm type-check
      - name: Lint
        working-directory: app
        run: pnpm lint
